### ISSUE TITLE
[Bug]: plugin-ytdl-player Bot crashes when pressing button `Queue`

### ISSUE THREAD

**Issue by vllirette** [discordx-ts/discordx#1057]
### What happened?

When pressing the button `Queue` the bot crashes but it should be showing the queue.

### Reproduction

Press the `Queue` button on the UI
![image](https://github.com/discordx-ts/discordx/assets/14930235/2d4e9137-f0e8-45f5-ae1b-df9f5f490ecb)

> Note: using the command `/music queue` doesn't make the bot crash.

### Package

plugin-ytdl-player

### Relevant log output

```Shell
/home/vllirette/projects/northcraft/northcraftbot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:187
    if (!this.deferred && !this.replied) return Promise.reject(new DiscordjsError(ErrorCodes.InteractionNotReplied));
                                                               ^
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ButtonInteraction.followUp (/home/vllirette/projects/northcraft/northcraftbot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:187:64)
    at Queue.view (file:///home/vllirette/projects/northcraft/northcraftbot/node_modules/@discordx/plugin-ytdl-player/src/queue.ts:283:38)
    at music.queueControl (file:///home/vllirette/projects/northcraft/northcraftbot/node_modules/@discordx/plugin-ytdl-player/src/index.ts:644:17)
    at next (file:///home/vllirette/projects/northcraft/northcraftbot/node_modules/discordx/dist/index.mjs:1081:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InteractionNotReplied'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samarmeena** [comment]
@vllirette should be fixed now. Thank you for reporting!

**Comment by vllirette** [comment]
@samarmeena Wow thanks for the fast response! It works 😃

**Comment by samarmeena** [comment]
@vllirette , thank you for your support. I'll be rewriting plugin-ytdl-player soon to improve the code. If you have any recommendations, please let me know.
