### ISSUE TITLE
[Bug]: The bot crashes with the command /music lyrics.

### ISSUE THREAD

**Issue by felipevelascohz** [discordx-ts/discordx#1077]
### What happened?

The bot crashes when using the **/music lyrics** command.

### Reproduction

The issue is related to the following [line](https://github.com/discordx-ts/discordx/blob/4bf6131212cbb10c142294ffc54234b4c8dc6f6a/packages/plugin-lava-player/src/plugins/lavalyrics/index.ts#L79). Locally, I modified that line to `const lyric = response.text`, and it works.

### Package

plugin-lava-player

### Relevant log output

```Shell
const lyric = response.lines.map((line) => line.line).join("\n");
                                     ^

TypeError: Cannot read properties of null (reading 'map')
    at Command.lyrics (file:///Users/felipevelasco/Learning/discord-bot/node_modules/@discordx/plugin-lava-player/dist/plugins/lavalyrics/index.js:61:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async next (file:///Users/felipevelasco/Learning/discord-bot/node_modules/discordx/dist/index.mjs:1093:15)

Node.js v22.8.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vijayymmeena** [comment]
@felipevelascohz are you using latest plugins? based on there README page of lyrics. `lines` should exist. Please verify the plugin version you are using. So that I can cross check.

Thank you.

**Comment by felipevelascohz** [comment]
These are the versions of the plugins I am using:

`plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.10.2"
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.1.1`

**Comment by vijayymmeena** [comment]
@felipevelascohz are you in our discordx discord server? if you are, please contact me there `@vijayymmeena`

I need to discuss additional details about the issue, as it seems more aspects of Lavalink are broken. I’d like to confirm these points with you.

Thank you

**Comment by vijayymmeena** [comment]
![image](https://github.com/user-attachments/assets/e4c6d341-2a94-45eb-9f90-109f693f5765)

@felipevelascohz I have tested. I am not able to verify your issue.

Also please upgrade plugin dependencies to latest.

```
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.3"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"
```
