### ISSUE TITLE
[Bug]: Broke the ESM build by merging #929 

### ISSUE THREAD

**Issue by TeamWolfyta** [discordx-ts/discordx#931]
### What happened?

You broke the ESM build by merging #929, ESM requires file extensions in the imports. I would revert #929 as from my understanding, You'd have to use a bundler to make use of tree-shaking, Discordx isn't bundled last I checked, It's built then published, Making the merge completely useless.

### Reproduction

Install latest version (11.7.2) and try and run it.

### Package

discordx

### Version

Stable

### Relevant log output

```Shell
> my-bot@1.0.0 dev /root/projects/teamwolfyta/my-bot
> ts-node-esm src/main.ts

/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
    throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module '/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/discordx@11.7.2_discord.js@14.8.0/node_modules/lodash/escapeRegExp' imported from /root/projects/teamwolfyta/my-bot/node_modules/.pnpm/discordx@11.7.2_discord.js@14.8.0/node_modules/discordx/build/esm/Client.js
    at finalizeResolution (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/esm.ts:168:34)
    at /root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/esm.ts:197:12)
    at resolve (/root/projects/teamwolfyta/my-bot/node_modules/.pnpm/ts-node@10.9.1_cbfmry4sbbh4vatmdrsmatfg5a/node_modules/ts-node/src/child/child-loader.ts:15:39)
    at nextResolve (node:internal/modules/esm/loader:163:28)
 ELIFECYCLE  Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TeamWolfyta** [comment]
Anyone else having this issue, Revert to the previous version. https://www.npmjs.com/package/discordx/v/11.7.1.
